version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: dockerfile
    image: ghcr.io/absalom-silwal/app.shortly
    container_name: url-shortner
    command: npx ts-node src/index.ts
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/url-shortner
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/app

      
  mongo:
    image: mongo:7.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  
  redis:
    image: redis:alpine
    ports: 
      - "6379:6379"

volumes:
  mongo-data:
