# Use official Node.js LTS image
FROM node:20-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the code
COPY . .

# Expose port
EXPOSE 5000

# Install TypeScript tools globally
RUN npm install -g ts-node typescript nodemon

# Start the app
CMD ["npm", "run", "dev"]
